name: Publish to PyPI

on:
  release:
    types:
      - created
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PDM
        run: pip install pdm

      - name: Install dependencies
        run: pdm install --production

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        run: pdm publish --username __token__ --password ${{ secrets.PDM_PYPI_PASSWORD }}
